// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJPcxGXm2Ep5BEAkvF2a3xjYrn67D6Ips',
    appId: '1:155277650651:web:c1788a6a1f11f7f7d0fafe',
    messagingSenderId: '155277650651',
    projectId: 'our-home-da',
    authDomain: 'our-home-da.firebaseapp.com',
    storageBucket: 'our-home-da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD998k4EBwA1A7b9gwFqw1oecikUecxPaQ',
    appId: '1:155277650651:android:5b80638488290ec5d0fafe',
    messagingSenderId: '155277650651',
    projectId: 'our-home-da',
    storageBucket: 'our-home-da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyUtSNyZqNsgNPF53y8iLMbt0IjdJ27X4',
    appId: '1:155277650651:ios:fb017aaa98f35c30d0fafe',
    messagingSenderId: '155277650651',
    projectId: 'our-home-da',
    storageBucket: 'our-home-da.firebasestorage.app',
    iosBundleId: 'com.example.ourHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyUtSNyZqNsgNPF53y8iLMbt0IjdJ27X4',
    appId: '1:155277650651:ios:fb017aaa98f35c30d0fafe',
    messagingSenderId: '155277650651',
    projectId: 'our-home-da',
    storageBucket: 'our-home-da.firebasestorage.app',
    iosBundleId: 'com.example.ourHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJPcxGXm2Ep5BEAkvF2a3xjYrn67D6Ips',
    appId: '1:155277650651:web:f96393066a3a27bcd0fafe',
    messagingSenderId: '155277650651',
    projectId: 'our-home-da',
    authDomain: 'our-home-da.firebaseapp.com',
    storageBucket: 'our-home-da.firebasestorage.app',
  );
}
